# Generated by Django 3.1.2 on 2020-10-16 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectModel',
            new_name='ProjectHamidBagheri',
        ),
    ]
